#!/bin/bash

loud() {
  local msg="Horizon firstboot: $1"
  echo -e "$msg" > /dev/console
  echo -e "$msg"
}

exists() {
  dpkg -l bluehorizon > /dev/null 2>&1
  echo $?
}

reachable() {
  host pkg.bluehorizon.network > /dev/null 2>&1
  echo $?
}

install() {
  # do install
  loud 'Installing Blue Horizon (this may take a few mins)'

  start=$(date +%s)
  evalct=0
  until [ "$(reachable)" == 0 ]; do
    sleep 20

    if [ $((evalct % 3)) -eq 0 ]; then
      loud "Repository unavailable, probably because this device is not connected to a network. Checking back again in a few seconds. This procedure will continue indefinitely; if you'd like to suspend the firstboot setup process, execute 'systemctl stop horizon-configure'. It will be re-executed on reboot."
    fi

    evalct=$((evalct+1))
  done


  EXIT=0
  until [ $(exists bluehorizon) == 0 ]; do
    wget -qO - http://pkg.bluehorizon.network/bluehorizon.network-public.key | sudo apt-key add -

    ls /var/cache/apt/archives/*horizon*.deb > /dev/null 2>&1

    if [ $? == 0 ]; then
      cd /var/cache/apt/archives/ && dpkg -i --force-confold horizon*.deb bluehorizon*.deb
      EXIT=$?
    else
      if [[ ! -e "/etc/apt/sources.list.d/bluehorizon.list" ]]; then

      cat <<EOF > /etc/apt/sources.list.d/bluehorizon.list
deb [arch=armhf] http://pkg.bluehorizon.network/linux/raspbian jessie main
deb-src [arch=armhf] http://pkg.bluehorizon.network/linux/raspbian jessie main
deb [arch=armhf] http://pkg.bluehorizon.network/linux/raspbian jessie-updates main
deb-src [arch=armhf] http://pkg.bluehorizon.network/linux/raspbian jessie-updates main
EOF
      fi
      apt-get update
      apt-get install -o Dpkg::Options::="--force-confold" -y bluehorizon
    fi

    start=$(date +%s)
    if [ $((start - $(date +%s))) -gt 120 ]; then
      loud 'ERROR: Unable to install Blue Horizon bundle.'
      continue 2
    fi
  done

  systemctl daemon-reload && systemctl enable horizon.service && systemctl start horizon.service
  EXIT=$?

  if [ $EXIT == 0 ]; then
    loud 'Successfully installed Blue Horizon bundle and started services.'
  else
    loud 'Failure to install Blue Horizon bundle. Please check system logs for more information.'
  fi
}

firstboot() {
  loud 'Starting firstboot configuration'

  loud 'Growing root partition'
  /usr/sbin/resize-root

  NEW_HOSTNAME=horizon-$(cat /proc/cpuinfo | grep Serial | head -1 | awk '{print $NF}')
  echo -e "\n127.0.1.1        ${NEW_HOSTNAME}" >> /etc/hosts
  echo "${NEW_HOSTNAME}" > /etc/hostname

  loud "Set hostname to $NEW_HOSTNAME"

  MIN=$((RANDOM % 60))
  HOUR0=$((RANDOM % 24))
  for i in {1..3}; do export HOUR${i}="$(( ($HOUR0+($i*6)) %24))"; done
  echo "0    3 * * *   root    find /var/log/workload -iname "*.gz" -mtime +32 -print0 | xargs -0 rm -f" >> /etc/crontab
  echo "30   3 * * *   root    find /var/log/workload -mtime +2 -size 0 -print0 | xargs -0 rm -f" >> /etc/crontab

}

main() {
  if  [ -e /var/horizon/.firstboot ]; then
    if [ "$(exists bluehorizon)" != 0 ]; then
      install
    fi
  else
    firstboot

    # do this stuff even if firstboot operations failed b/c there is risk of getting caught in a boot loop
    mkdir -p /var/horizon
    touch /var/horizon/.firstboot

    loud 'Firstboot setup procedure complete, rebooting'
    systemctl reboot
  fi
}

main | systemd-cat -t horizon-install
